[package]
name = "gameboy"
version = "0.1.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2018"

[dependencies]
argparse = "0.2"
blip_buf = "0.1"
cpal = "0.8"
glium = { version = "0.22", default_features = false, features = [ "glutin" ] }
rog = "0.1"
